[project]
name = "astro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deltalake>=0.22.0",
    "duckdb>=1.1.3",
    "ipykernel>=6.29.5",
    "ruff>=0.8.0",
]
